### ISSUE TITLE
Failed to install because of "Error in read.dcf(path)"

### ISSUE THREAD

**Issue by Supermem** [braverock/FactorAnalytics#2] opened 2018-12-14 03:27 UTC
Error in read.dcf(path) : 
  Found continuation line starting '    time series, fun ...' at begin of record. 
10. read.dcf(path) 
9.   is.data.frame(x) 
8.   colnames(read.dcf(path)) 
7.   read_dcf(tmp) 
6. remote_package_name.github_remote(remote) 
5. remote_package_name(remote) 
4. FUN(X[[i]], ...) 
3. vapply(remotes, install_remote, ..., FUN.VALUE = character(1)) 
2.
install_remotes(remotes, auth_token = auth_token, host = host, 
    dependencies = dependencies, upgrade = upgrade, force = force, 
    quiet = quiet, build = build, build_opts = build_opts, repos = repos, 
    type = type, ...) 
1.
devtools::install_github("braverock/factorAnalytics")

**Comment by kkumawat25** [comment] 2019-11-18 17:15
Unable to install, it says the package is not available
' package ‘factorAnalytics’ is not available (for R version 3.6.1)'

**Comment by midoshammaa** [comment] 2019-11-19 03:39
I am unable to replicate the issue.  Ijust got a fresh install of R 3.6.1
and tried.  What is your data.table version?

**Comment by kecoli** [comment] 2020-07-17 05:18
> devtools::install_github("braverock/factorAnalytics")

not able to reproduce, pending to close the issue

**Comment by kecoli** [comment] 2020-07-17 05:20
> Unable to install, it says the package is not available
> ' package ‘factorAnalytics’ is not available (for R version 3.6.1)'

try the updated package name FactorAnalytics

**Closed as completed** 2020-07-17 05:20 UTC
